In [4]:
import numpy as np
import scipy as sp
from numpy import array as arr

6-Decision

FI91 - Koreshkov - variant 6

In [5]:
factors = arr([0.4, 0.6])

In [9]:
R1 = arr([
    [1, 0.3, 0.8, 0.5, 1],
    [0.6, 1, 0.3, 0.8, 0.7],
    [0.8, 0.5, 1, 0.9, 0.6],
    [0.7, 0.5, 0.6, 1, 0.4],
    [0.2, 0.3, 0.1, 0.4, 1],
])
R2 = arr([
    [1, 0, 1, 0, 0.6],
    [1, 1, 0.9, 0.4, 1],
    [0, 0.7, 1, 0, 0.7],
    [0.5, 0.3, 0, 1, 0.7],
    [1, 0.9, 0.8, 0.3, 1],
])


In [10]:
def intersect(A, B):
    return np.minimum(A, B)

In [11]:
def strongify(R):
    return np.minimum(np.maximum(R  - R.T, 0), 1)

In [13]:
Q1 = intersect(0.4*R1, 0.6*R2)
Q1

array([[0.4 , 0.  , 0.32, 0.  , 0.36],
       [0.24, 0.4 , 0.12, 0.24, 0.28],
       [0.  , 0.2 , 0.4 , 0.  , 0.24],
       [0.28, 0.18, 0.  , 0.4 , 0.16],
       [0.08, 0.12, 0.04, 0.16, 0.4 ]])

In [14]:
Q1s = strongify(Q1)
Q1s

array([[0.  , 0.  , 0.32, 0.  , 0.28],
       [0.24, 0.  , 0.  , 0.06, 0.16],
       [0.  , 0.08, 0.  , 0.  , 0.2 ],
       [0.28, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  ]])

In [26]:
def nd(Q):
    return 1 - Q.max(axis=1)

In [21]:
Q1_nd = nd(Q1s)
Q1_nd

array([0.68, 0.76, 0.8 , 0.72, 1.  ])

In [22]:
Q2 = 0.4 * R1 + 0.6 * R2
Q2

array([[1.  , 0.12, 0.92, 0.2 , 0.76],
       [0.84, 1.  , 0.66, 0.56, 0.88],
       [0.32, 0.62, 1.  , 0.36, 0.66],
       [0.58, 0.38, 0.24, 1.  , 0.58],
       [0.68, 0.66, 0.52, 0.34, 1.  ]])

In [23]:
Q2s = strongify(Q2)
Q2s

array([[0.  , 0.  , 0.6 , 0.  , 0.08],
       [0.72, 0.  , 0.04, 0.18, 0.22],
       [0.  , 0.  , 0.  , 0.12, 0.14],
       [0.38, 0.  , 0.  , 0.  , 0.24],
       [0.  , 0.  , 0.  , 0.  , 0.  ]])

In [24]:
Q2_nd = nd(Q2s)
Q2_nd

array([0.4 , 0.28, 0.86, 0.62, 1.  ])

In [27]:
mu = np.minimum(Q1_nd, Q2_nd)
mu

array([0.4 , 0.28, 0.8 , 0.62, 1.  ])

In [28]:
mu.argmax()

4

In [32]:
np.flip(mu.argsort())

array([4, 2, 3, 0, 1], dtype=int64)

**Отже, найкращим вибором буде $x_5$. Далі $x_3, x_4, x_1$ та $x_2$**