In [6]:
import numpy as np
import itertools as it
import simplex1 as s

In [7]:
A = np.array([
    [1, 1, -3],
    [3, -1, -5],
    [0, -1, 4],
    [-3, -2, 26],
    [-1, 3, 5],
    [-1, -3, 0]
])
A

array([[ 1,  1, -3],
       [ 3, -1, -5],
       [ 0, -1,  4],
       [-3, -2, 26],
       [-1,  3,  5],
       [-1, -3,  0]])

# Simplex

In [8]:
A = np.array([
    [1, 1, -3],
    [3, -1, -5],
    [0, -1, 4],
    [-3, -2, 26],
    [-1, 3, 5],
    [1, -3, 0],
])
basis = ['x1', 'x2', '1']
nonbasis = ['y1', 'y2', 'y3', 'y4', 'y5', 'F']

In [9]:
s.jordan_swap(A, 0,0)

array([[ 1., -1.,  3.],
       [ 3., -4.,  4.],
       [ 0., -1.,  4.],
       [-3.,  1., 17.],
       [-1.,  4.,  2.],
       [ 1., -4.,  3.]])

In [14]:
A = np.array([
    [1, -1, 3],
    [3, -4, 4],
    [0, -1, 4],
    [-3, 1, 17],
    [-1, 4, 2],
    [1, -4, 3],
])
# A = np.hstack([A,A+0.5])

print(A)



[[ 1 -1  3]
 [ 3 -4  4]
 [ 0 -1  4]
 [-3  1 17]
 [-1  4  2]
 [ 1 -4  3]]


(1, 1)

In [14]:
g = np.array([-1,0,1])
g > 10
g>10

array([False, False, False])