In [1]:
import numpy as np
import scipy as sp
import scipy.stats

In [3]:
n = 5
cost = np.array([
    [34, 26, 29, 31],
    [42, 33, 28, 35],
    [36, 29, 32, 38]
])

b1 = np.array([200, 250, 350, 300]) # >=
b2= np.array([500, 400, 400]) # <=

In [4]:
obj = cost.flatten()
obj

array([34, 26, 29, 31, 42, 33, 28, 35, 36, 29, 32, 38])

In [9]:
Ale = np.zeros((3, 12))
Ale[0,0] = Ale[0,1] = Ale[0,2] = Ale[0,3] = 1
Ale[1,4+0] = Ale[1,4+1] = Ale[1,4+2] = Ale[1,4+3] = 1
Ale[2,8+0] = Ale[2,8+1] = Ale[2,8+2] = Ale[2,8+3] = 1

ble = np.array([500, 400, 400])

Ale, ble

(array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]]),
 array([500, 400, 400]))

In [10]:
Aq = np.zeros((4, 12))
Aq[0,0] = Aq[0,4] = Aq[0,8] = 1
Aq[1,1] = Aq[1,5] = Aq[1,9] = 1
Aq[2,2] = Aq[2,6] = Aq[2,10] = 1
Aq[3,3] = Aq[3,7] = Aq[3,11] = 1

bq = np.array([200, 250, 350, 300])

Aq, bq

(array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.]]),
 array([200, 250, 350, 300]))

In [11]:
ans = sp.optimize.linprog(obj, Ale, ble, Aq, bq)
ans

     con: array([2.80079936e-06, 3.51163146e-06, 4.93335375e-06, 4.22253396e-06])
     fun: 32949.99954394596
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([7.40444045e-06, 5.00000030e+01, 1.50000005e+02])
  status: 0
 success: True
       x: array([8.15125298e-07, 1.99999998e+02, 4.73276846e-08, 2.99999994e+02,
       2.39091658e-07, 2.09428092e-07, 3.49999995e+02, 1.63991594e-06,
       1.99999996e+02, 4.99999985e+01, 1.05474611e-07, 1.90067388e-07])

In [14]:
X = np.round(ans.x, 4).reshape((3,4))
X

array([[  0., 200.,   0., 300.],
       [  0.,   0., 350.,   0.],
       [200.,  50.,   0.,   0.]])

In [15]:
X.sum(axis=1)

array([500., 350., 250.])