In [15]:
import numpy as np
import scipy as sp
import scipy.stats

In [56]:
n = 5
interest = np.array([
    0.140, 0.130, 0.120, 0.125, 0.1
])

bad = np.array([
    0.1, 0.07, 0.03, 0.05, 0.02
])
total = 10

In [66]:
A_le = np.array([
    [0.,0, 0, -1, -1], # >= 0.3 * total
    [0.4, 0.4, -0.6, 0, 0], # <= 0
    [0.1, 0.07, 0.03, 0.05, 0.02], # <= 0.04
    [1, 1, 1, 1, 1] # <= 10
])
A_le[0] += 0.3
A_le[2] -= 0.04

b_le = np.array([ 0, 0, 0, 10 ])

In [67]:
net = interest * (1-bad) - bad

In [68]:
A_le, b_le

(array([[ 0.3 ,  0.3 ,  0.3 , -0.7 , -0.7 ],
        [ 0.4 ,  0.4 , -0.6 ,  0.  ,  0.  ],
        [ 0.06,  0.03, -0.01,  0.01, -0.02],
        [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ]]),
 array([ 0,  0,  0, 10]))

In [61]:
ans = sp.optimize.linprog(-net, A_le, b_le)
ans

     con: array([], dtype=float64)
     fun: -0.8387999788630413
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([2.66225444e-07, 4.19999955e+00, 1.29999988e-01, 8.58602576e-08])
  status: 0
 success: True
       x: array([1.05494514e-07, 1.48383943e-07, 6.99999942e+00, 6.40085543e-09,
       3.00000023e+00])

In [62]:
np.round(ans.x, 4)

array([0., 0., 7., 0., 3.])

In [23]:
net

array([0.026  , 0.0509 , 0.0864 , 0.06875, 0.078  ])

In [64]:
np.array([0,1,0,0,0]) @ net

0.05089999999999999