In [1]:
import numpy as np

In [21]:
# fzzy_ge - uncertain weak advantage relation
def decide(fuzzy_ge):
    # let's find xs that are not dominated.
    # of course, set of this xs will be fuzzy.
    # mu(x) = 1 - sup_y( ge(y,x) - ge(x,y) )
    fuzzy_gr = fuzzy_ge - fuzzy_ge.T
    fuzzy_max = fuzzy_gr.max(axis=0)
    return 1 - fuzzy_max

In [22]:
E = np.array([
    [1, 0.4, 0.6, 0],
    [1, 1, 0.8, 1],
    [0.2, 1, 1, 1],
    [0.8, 0, 0, 1]
])

A1 = np.array([
    [1, 0.8, 1, 0],
    [0, 1, 0.2, 1],
    [0, 0.8, 1, 0],
    [0, 0, 0, 1]
])
A2 = np.array([
    [1, 0.4, 0.5, 0.3],
    [0.8, 1, 0.8, 0.8],
    [0.5, 1, 1,0 ],
    [0.8, 0, 0, 1],
])
A3 = np.array([
    [1, 0, 0.8, 0],
    [0, 1, 0, 0],
    [0.1, 0, 1, 0.4],
    [1, 0, 1, 1]
])
A4 = np.array([
    [1, 1, 0.9, 0],
    [0, 1, 1, 1],
    [0.4, 0, 1, 0],
    [0, 0, 0, 1]
])

A = (A1, A2, A3, A4)

In [26]:
decisions = np.array([decide(a) for a in A])
decisions
# a_ij = i-th expert's decision about j-th alternative

array([[1. , 0.2, 0. , 0. ],
       [0.5, 0.8, 1. , 0.2],
       [0. , 1. , 0.3, 1. ],
       [1. , 0. , 0. , 0. ]])

In [32]:
expert_trust = decide(E)
expert_trust /= expert_trust.sum()
expert_trust
# more - more trustworthy expert is

array([0.125, 0.5  , 0.375, 0.   ])

In [34]:
final_decision = expert_trust @ decisions
final_decision

array([0.375 , 0.8   , 0.6125, 0.475 ])