In [1]:
import numpy as np

In [3]:
m = np.array([2,1,1])
A = np.array([
    [16, 1, -1],
    [1, 4, -1],
    [-1, -1,9],
])
B = np.array([
    [3, 2, 0],
    [2, 0, -2]
])

In [4]:
m1 = B @ m
m1

array([8, 2])

In [5]:
A1 = B @ A @ B.T
A1

array([[172, 110],
       [110, 108]])

In [9]:
D = np.array([
    [1, -2],
    [-2, 9]
])
D1 = np.linalg.inv(D)

In [7]:
np.linalg.det(D)

5.000000000000001

In [10]:
np.array([-1,1]) @ D1

array([-1.4, -0.2])